%General Mission Analysis Tool(GMAT) Script
%Created: 2026-08-25 10:37:38


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft GEOSAT;
GEOSAT.DateFormat = TAIModJulian;
GEOSAT.Epoch = '21545';
GEOSAT.CoordinateSystem = EarthMJ2000Eq;
GEOSAT.DisplayStateType = Keplerian;
GEOSAT.SMA = 42164.17000000003;
GEOSAT.ECC = 5.612411358545992e-17;
GEOSAT.INC = 0;
GEOSAT.RAAN = 0;
GEOSAT.AOP = 0;
GEOSAT.TA = 120;
GEOSAT.DryMass = 1800;
GEOSAT.Cd = 2.2;
GEOSAT.Cr = 1.8;
GEOSAT.DragArea = 15;
GEOSAT.SRPArea = 1;
GEOSAT.SPADDragScaleFactor = 1;
GEOSAT.SPADSRPScaleFactor = 1;
GEOSAT.AtmosDensityScaleFactor = 1;
GEOSAT.ExtendedMassPropertiesModel = 'None';
GEOSAT.Tanks = {ElectricTank1};
GEOSAT.Thrusters = {ElectricThruster1, ElectricThruster2, ElectricThruster3, ElectricThruster4};
GEOSAT.PowerSystem = SolarPowerSystem1;
GEOSAT.NAIFId = -10021001;
GEOSAT.NAIFIdReferenceFrame = -9021001;
GEOSAT.OrbitColor = Red;
GEOSAT.TargetColor = Teal;
GEOSAT.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GEOSAT.CdSigma = 1e+70;
GEOSAT.CrSigma = 1e+70;
GEOSAT.Id = 'SatId';
GEOSAT.Attitude = CoordinateSystemFixed;
GEOSAT.SPADSRPInterpolationMethod = Bilinear;
GEOSAT.SPADSRPScaleFactorSigma = 1e+70;
GEOSAT.SPADDragInterpolationMethod = Bilinear;
GEOSAT.SPADDragScaleFactorSigma = 1e+70;
GEOSAT.AtmosDensityScaleFactorSigma = 1e+70;
GEOSAT.ModelFile = 'aura.3ds';
GEOSAT.ModelOffsetX = 0;
GEOSAT.ModelOffsetY = 0;
GEOSAT.ModelOffsetZ = 0;
GEOSAT.ModelRotationX = 0;
GEOSAT.ModelRotationY = 0;
GEOSAT.ModelRotationZ = 0;
GEOSAT.ModelScale = 1;
GEOSAT.AttitudeDisplayStateType = 'Quaternion';
GEOSAT.AttitudeRateDisplayStateType = 'AngularVelocity';
GEOSAT.AttitudeCoordinateSystem = EarthMJ2000Eq;
GEOSAT.EulerAngleSequence = '321';

%----------------------------------------
%---------- Hardware Components
%----------------------------------------


Create ElectricTank ElectricTank1;
ElectricTank1.DirectionX = 0;
ElectricTank1.DirectionY = 0;
ElectricTank1.DirectionZ = 1;
ElectricTank1.SecondDirectionX = 0;
ElectricTank1.SecondDirectionY = -1;
ElectricTank1.SecondDirectionZ = 0;
ElectricTank1.HWOriginInBCSX = 0;
ElectricTank1.HWOriginInBCSY = 0;
ElectricTank1.HWOriginInBCSZ = 0;
ElectricTank1.AllowNegativeFuelMass = true;
ElectricTank1.FuelMass = 756;
ElectricTank1.FuelCenterOfMassX = 0;
ElectricTank1.FuelCenterOfMassY = 0;
ElectricTank1.FuelCenterOfMassZ = 0;
ElectricTank1.FuelMomentOfInertiaXX = 99;
ElectricTank1.FuelMomentOfInertiaXY = 0;
ElectricTank1.FuelMomentOfInertiaXZ = 0;
ElectricTank1.FuelMomentOfInertiaYY = 99;
ElectricTank1.FuelMomentOfInertiaYZ = 0;
ElectricTank1.FuelMomentOfInertiaZZ = 99;

Create ElectricThruster ElectricThruster1;
ElectricThruster1.HWOriginInBCSX = 0;
ElectricThruster1.HWOriginInBCSY = 0;
ElectricThruster1.HWOriginInBCSZ = 0;
ElectricThruster1.CoordinateSystem = Local;
ElectricThruster1.Origin = Earth;
ElectricThruster1.Axes = VNB;
ElectricThruster1.ThrustDirection1 = 1;
ElectricThruster1.ThrustDirection2 = 0;
ElectricThruster1.ThrustDirection3 = 0;
ElectricThruster1.DutyCycle = 1;
ElectricThruster1.ThrustScaleFactor = 1;
ElectricThruster1.DecrementMass = true;
ElectricThruster1.Tank = {ElectricTank1};
ElectricThruster1.MixRatio = [ 1 ];
ElectricThruster1.GravitationalAccel = 9.81;
ElectricThruster1.ThrustModel = ConstantThrustAndIsp;
ElectricThruster1.MaximumUsablePower = 7.266;
ElectricThruster1.MinimumUsablePower = 0.638;
ElectricThruster1.ThrustCoeff1 = -5.19082;
ElectricThruster1.ThrustCoeff2 = 2.96519;
ElectricThruster1.ThrustCoeff3 = -14.4789;
ElectricThruster1.ThrustCoeff4 = 54.05382;
ElectricThruster1.ThrustCoeff5 = -0.00100092;
ElectricThruster1.MassFlowCoeff1 = -0.004776;
ElectricThruster1.MassFlowCoeff2 = 0.05717;
ElectricThruster1.MassFlowCoeff3 = -0.09956;
ElectricThruster1.MassFlowCoeff4 = 0.03211;
ElectricThruster1.MassFlowCoeff5 = 2.13781;
ElectricThruster1.FixedEfficiency = 0.7;
ElectricThruster1.Isp = 4200;
ElectricThruster1.ConstantThrust = 0.237;

Create ElectricThruster ElectricThruster2;
ElectricThruster2.HWOriginInBCSX = 0;
ElectricThruster2.HWOriginInBCSY = 0;
ElectricThruster2.HWOriginInBCSZ = 0;
ElectricThruster2.CoordinateSystem = Local;
ElectricThruster2.Origin = Earth;
ElectricThruster2.Axes = VNB;
ElectricThruster2.ThrustDirection1 = -1;
ElectricThruster2.ThrustDirection2 = 0;
ElectricThruster2.ThrustDirection3 = 0;
ElectricThruster2.DutyCycle = 1;
ElectricThruster2.ThrustScaleFactor = 1;
ElectricThruster2.DecrementMass = true;
ElectricThruster2.Tank = {ElectricTank1};
ElectricThruster2.MixRatio = [ 1 ];
ElectricThruster2.GravitationalAccel = 9.81;
ElectricThruster2.ThrustModel = ConstantThrustAndIsp;
ElectricThruster2.MaximumUsablePower = 7.266;
ElectricThruster2.MinimumUsablePower = 0.638;
ElectricThruster2.ThrustCoeff1 = -5.19082;
ElectricThruster2.ThrustCoeff2 = 2.96519;
ElectricThruster2.ThrustCoeff3 = -14.4789;
ElectricThruster2.ThrustCoeff4 = 54.05382;
ElectricThruster2.ThrustCoeff5 = -0.00100092;
ElectricThruster2.MassFlowCoeff1 = -0.004776;
ElectricThruster2.MassFlowCoeff2 = 0.05717;
ElectricThruster2.MassFlowCoeff3 = -0.09956;
ElectricThruster2.MassFlowCoeff4 = 0.03211;
ElectricThruster2.MassFlowCoeff5 = 2.13781;
ElectricThruster2.FixedEfficiency = 0.7;
ElectricThruster2.Isp = 4200;
ElectricThruster2.ConstantThrust = 0.237;

Create SolarPowerSystem SolarPowerSystem1;
SolarPowerSystem1.EpochFormat = 'UTCGregorian';
SolarPowerSystem1.InitialEpoch = ''01 Jan 2000 11:59:28.000'';
SolarPowerSystem1.InitialMaxPower = 1.2;
SolarPowerSystem1.AnnualDecayRate = 5;
SolarPowerSystem1.Margin = 5;
SolarPowerSystem1.BusCoeff1 = 0.3;
SolarPowerSystem1.BusCoeff2 = 0;
SolarPowerSystem1.BusCoeff3 = 0;
SolarPowerSystem1.ShadowModel = 'None';
SolarPowerSystem1.ShadowBodies = {'Earth'};
SolarPowerSystem1.SolarCoeff1 = 1.32077;
SolarPowerSystem1.SolarCoeff2 = -0.10848;
SolarPowerSystem1.SolarCoeff3 = -0.11665;
SolarPowerSystem1.SolarCoeff4 = 0.10843;
SolarPowerSystem1.SolarCoeff5 = -0.01279;

Create ElectricThruster ElectricThruster3;
ElectricThruster3.HWOriginInBCSX = 0;
ElectricThruster3.HWOriginInBCSY = 0;
ElectricThruster3.HWOriginInBCSZ = 0;
ElectricThruster3.CoordinateSystem = Local;
ElectricThruster3.Origin = Earth;
ElectricThruster3.Axes = VNB;
ElectricThruster3.ThrustDirection1 = 0;
ElectricThruster3.ThrustDirection2 = 1;
ElectricThruster3.ThrustDirection3 = 0;
ElectricThruster3.DutyCycle = 1;
ElectricThruster3.ThrustScaleFactor = 1;
ElectricThruster3.DecrementMass = true;
ElectricThruster3.Tank = {ElectricTank1};
ElectricThruster3.MixRatio = [ 1 ];
ElectricThruster3.GravitationalAccel = 9.81;
ElectricThruster3.ThrustModel = ConstantThrustAndIsp;
ElectricThruster3.MaximumUsablePower = 7.266;
ElectricThruster3.MinimumUsablePower = 0.638;
ElectricThruster3.ThrustCoeff1 = -5.19082;
ElectricThruster3.ThrustCoeff2 = 2.96519;
ElectricThruster3.ThrustCoeff3 = -14.4789;
ElectricThruster3.ThrustCoeff4 = 54.05382;
ElectricThruster3.ThrustCoeff5 = -0.00100092;
ElectricThruster3.MassFlowCoeff1 = -0.004776;
ElectricThruster3.MassFlowCoeff2 = 0.05717;
ElectricThruster3.MassFlowCoeff3 = -0.09956;
ElectricThruster3.MassFlowCoeff4 = 0.03211;
ElectricThruster3.MassFlowCoeff5 = 2.13781;
ElectricThruster3.FixedEfficiency = 0.7;
ElectricThruster3.Isp = 4200;
ElectricThruster3.ConstantThrust = 0.237;

Create ElectricThruster ElectricThruster4;
ElectricThruster4.HWOriginInBCSX = 0;
ElectricThruster4.HWOriginInBCSY = 0;
ElectricThruster4.HWOriginInBCSZ = 0;
ElectricThruster4.CoordinateSystem = Local;
ElectricThruster4.Origin = Earth;
ElectricThruster4.Axes = VNB;
ElectricThruster4.ThrustDirection1 = 0;
ElectricThruster4.ThrustDirection2 = -1;
ElectricThruster4.ThrustDirection3 = 0;
ElectricThruster4.DutyCycle = 1;
ElectricThruster4.ThrustScaleFactor = 1;
ElectricThruster4.DecrementMass = true;
ElectricThruster4.Tank = {ElectricTank1};
ElectricThruster4.MixRatio = [ 1 ];
ElectricThruster4.GravitationalAccel = 9.81;
ElectricThruster4.ThrustModel = ConstantThrustAndIsp;
ElectricThruster4.MaximumUsablePower = 7.266;
ElectricThruster4.MinimumUsablePower = 0.638;
ElectricThruster4.ThrustCoeff1 = -5.19082;
ElectricThruster4.ThrustCoeff2 = 2.96519;
ElectricThruster4.ThrustCoeff3 = -14.4789;
ElectricThruster4.ThrustCoeff4 = 54.05382;
ElectricThruster4.ThrustCoeff5 = -0.00100092;
ElectricThruster4.MassFlowCoeff1 = -0.004776;
ElectricThruster4.MassFlowCoeff2 = 0.05717;
ElectricThruster4.MassFlowCoeff3 = -0.09956;
ElectricThruster4.MassFlowCoeff4 = 0.03211;
ElectricThruster4.MassFlowCoeff5 = 2.13781;
ElectricThruster4.FixedEfficiency = 0.7;
ElectricThruster4.Isp = 4200;
ElectricThruster4.ConstantThrust = 0.237;

























%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.PointMasses = {Luna, Sun};
DefaultProp_ForceModel.SRP = On;
DefaultProp_ForceModel.RelativisticCorrection = On;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';
DefaultProp_ForceModel.SRP.Flux = 1367;
DefaultProp_ForceModel.SRP.SRPModel = Spherical;
DefaultProp_ForceModel.SRP.Nominal_Sun = 149597870.691;
DefaultProp_ForceModel.Drag.AtmosphereModel = MSISE90;
DefaultProp_ForceModel.Drag.HistoricWeatherSource = 'ConstantFluxAndGeoMag';
DefaultProp_ForceModel.Drag.PredictedWeatherSource = 'ConstantFluxAndGeoMag';
DefaultProp_ForceModel.Drag.CSSISpaceWeatherFile = 'SpaceWeather-All-v1.2.txt';
DefaultProp_ForceModel.Drag.SchattenFile = 'SchattenPredict.txt';
DefaultProp_ForceModel.Drag.F107 = 150;
DefaultProp_ForceModel.Drag.F107A = 150;
DefaultProp_ForceModel.Drag.MagneticIndex = 3;
DefaultProp_ForceModel.Drag.SchattenErrorModel = 'Nominal';
DefaultProp_ForceModel.Drag.SchattenTimingModel = 'NominalCycle';
DefaultProp_ForceModel.Drag.DragModel = 'Spherical';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create FiniteBurn FiniteBurn1;
FiniteBurn1.Thrusters = {ElectricThruster1};
FiniteBurn1.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters';

Create FiniteBurn FiniteBurn2;
FiniteBurn2.Thrusters = {ElectricThruster2};
FiniteBurn2.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters';

Create FiniteBurn FiniteBurn3;
FiniteBurn3.Thrusters = {ElectricThruster3};
FiniteBurn3.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters';

Create FiniteBurn FiniteBurn4;
FiniteBurn4.Thrusters = {ElectricThruster4};
FiniteBurn4.ThrottleLogicAlgorithm = 'MaxNumberOfThrusters';


%----------------------------------------
%---------- Solvers
%----------------------------------------

Create DifferentialCorrector DefaultDC;
DefaultDC.ShowProgress = true;
DefaultDC.ReportStyle = Normal;
DefaultDC.ReportFile = 'DifferentialCorrectorDefaultDC.data';
DefaultDC.MaximumIterations = 25;
DefaultDC.DerivativeMethod = ForwardDifference;
DefaultDC.Algorithm = NewtonRaphson;

%----------------------------------------
%---------- Subscribers
%----------------------------------------


Create XYPlot XYPlot2;
XYPlot2.SolverIterations = Current;
XYPlot2.UpperLeft = [ 0.006341463414634147 0.3465250965250965 ];
XYPlot2.Size = [ 0.6707317073170732 0.305019305019305 ];
XYPlot2.RelativeZOrder = 4568;
XYPlot2.Maximized = false;
XYPlot2.XVariable = GEOSAT.ElapsedDays;
XYPlot2.YVariables = {GEOSAT.Earth.Latitude, targetlatitude, mlatitude, Mlatitude};
XYPlot2.ShowGrid = true;
XYPlot2.ShowPlot = true;

Create XYPlot XYPlot3;
XYPlot3.SolverIterations = Current;
XYPlot3.UpperLeft = [ 0.005853658536585366 0.6303088803088803 ];
XYPlot3.Size = [ 0.6809756097560976 0.3117760617760618 ];
XYPlot3.RelativeZOrder = 4728;
XYPlot3.Maximized = false;
XYPlot3.XVariable = GEOSAT.ElapsedDays;
XYPlot3.YVariables = {GEOSAT.EarthMJ2000Eq.INC, sat_INC, MINC, mINC};
XYPlot3.ShowGrid = true;
XYPlot3.ShowPlot = true;

Create XYPlot XYPlot4;
XYPlot4.SolverIterations = Current;
XYPlot4.UpperLeft = [ 0.01268292682926829 0.0222007722007722 ];
XYPlot4.Size = [ 0.6575609756097561 0.3310810810810811 ];
XYPlot4.RelativeZOrder = 4534;
XYPlot4.Maximized = false;
XYPlot4.XVariable = GEOSAT.ElapsedDays;
XYPlot4.YVariables = {GEOSAT.Earth.Longitude, targetlongitude, Mlongitude, mlongitude, X};
XYPlot4.ShowGrid = true;
XYPlot4.ShowPlot = true;

Create XYPlot XYPlot5;
XYPlot5.SolverIterations = Current;
XYPlot5.UpperLeft = [ 0.6848780487804879 0.0222007722007722 ];
XYPlot5.Size = [ 0.2839024390243902 0.2142857142857143 ];
XYPlot5.RelativeZOrder = 4539;
XYPlot5.Maximized = false;
XYPlot5.XVariable = GEOSAT.ElapsedDays;
XYPlot5.YVariables = {GEOSAT.ElectricThruster1.Isp, GEOSAT.ElectricThruster2.Isp, GEOSAT.ElectricThruster3.Isp, GEOSAT.ElectricThruster4.Isp};
XYPlot5.ShowGrid = true;
XYPlot5.ShowPlot = true;

Create XYPlot XYPlot7;
XYPlot7.SolverIterations = Current;
XYPlot7.UpperLeft = [ 0.3990243902439025 0.5540540540540541 ];
XYPlot7.Size = [ 0.5234146341463415 0.4391891891891892 ];
XYPlot7.RelativeZOrder = 4396;
XYPlot7.Maximized = false;
XYPlot7.XVariable = GEOSAT.ElapsedDays;
XYPlot7.YVariables = {GEOSAT.ElectricTank1.FuelMass};
XYPlot7.ShowGrid = true;
XYPlot7.ShowPlot = true;

%----------------------------------------
%---------- Arrays, Variables, Strings
%----------------------------------------
Create Variable tolereance_ecc tolerance_northsouth tolerance_eastwest daysofOK Mlongitude mlongitude targetlongitude sat_INC MINC mINC;
Create Variable Mlatitude mlatitude targetlatitude targetECC MECC mECC proptime1 proptime2 eLONG eLONGcorrected;
Create Variable burnduration X eECC eINC Y;
Create String a b;
tolereance_ecc = 0.004;
tolerance_northsouth = 0.1;
tolerance_eastwest = 0.1;
daysofOK = 300;
Mlongitude = 0;
mlongitude = 0;
targetlongitude = 0;
sat_INC = 0;
MINC = 0;
mINC = 0;
Mlatitude = 0;
mlatitude = 0;
targetlatitude = 0;
targetECC = 0;
MECC = 0;
mECC = 0;
proptime1 = 0;
proptime2 = 0;
eLONG = 0;
eLONGcorrected = 0;
burnduration = 1600;
X = 0;
eECC = 0;
eINC = 0;
Y = 0;
a = 'a';
b = 'b';



%----------------------------------------
%---------- User Objects
%----------------------------------------

Create OpenFramesView OrbitView1_View;
OrbitView1_View.ViewFrame = CoordinateSystem;
OrbitView1_View.ViewTrajectory = Off;
OrbitView1_View.InertialFrame = Off;
OrbitView1_View.SetDefaultLocation = On;
OrbitView1_View.DefaultEye = [ 30000 0 0 ];
OrbitView1_View.DefaultCenter = [ 0 0 0 ];
OrbitView1_View.DefaultUp = [ 0 0 1 ];
OrbitView1_View.SetCurrentLocation = Off;
OrbitView1_View.FOVy = 45;

Create OpenFramesView NewView2;
NewView2.ViewFrame = Earth;
NewView2.ViewTrajectory = Off;
NewView2.InertialFrame = Off;
NewView2.SetDefaultLocation = Off;
NewView2.SetCurrentLocation = On;
NewView2.CurrentEye = [ 47106.45241674146 -37803.3360583706 11433.31410862052 ];
NewView2.CurrentCenter = [ 0 3.637978807091713e-11 -1.091393642127514e-11 ];
NewView2.CurrentUp = [ -0.04629214246546121 0.2358890693215285 0.9706767662412553 ];
NewView2.FOVy = 45;

Create OpenFramesView NewView3;
NewView3.ViewFrame = GEOSAT;
NewView3.ViewTrajectory = Off;
NewView3.InertialFrame = Off;
NewView3.SetDefaultLocation = Off;
NewView3.SetCurrentLocation = Off;
NewView3.FOVy = 45;

Create OpenFramesView NewView1;
NewView1.ViewFrame = GEOSAT;
NewView1.ViewTrajectory = Off;
NewView1.InertialFrame = Off;
NewView1.SetDefaultLocation = Off;
NewView1.SetCurrentLocation = On;
NewView1.CurrentEye = [ -21671.021322198 -1257.879820450689 -3247.4269510228 ];
NewView1.CurrentCenter = [ 12.50000000001455 237.2500000000189 118.4999999999795 ];
NewView1.CurrentUp = [ -0.1078058523844734 -0.4416665916563636 0.8906786850521956 ];
NewView1.FOVy = 45;

Create OpenFramesView NewView4;
NewView4.ViewFrame = GEOSAT;
NewView4.ViewTrajectory = Off;
NewView4.InertialFrame = Off;
NewView4.SetDefaultLocation = Off;
NewView4.SetCurrentLocation = On;
NewView4.CurrentEye = [ -1008.379263368065 -42275.36585422426 36655.36732776287 ];
NewView4.CurrentCenter = [ 12.49999999999829 237.2500000000437 118.4999999999854 ];
NewView4.CurrentUp = [ -0.1804725440273197 0.6435799345729305 0.7437973707048241 ];
NewView4.FOVy = 45;

Create OpenFramesView OrbitView2_View;
OrbitView2_View.ViewFrame = CoordinateSystem;
OrbitView2_View.ViewTrajectory = Off;
OrbitView2_View.InertialFrame = Off;
OrbitView2_View.SetDefaultLocation = On;
OrbitView2_View.DefaultEye = [ 30000 0 0 ];
OrbitView2_View.DefaultCenter = [ 0 0 0 ];
OrbitView2_View.DefaultUp = [ 0 0 1 ];
OrbitView2_View.SetCurrentLocation = Off;
OrbitView2_View.FOVy = 45;



%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
targetlongitude = GEOSAT.Earth.Longitude;
Mlongitude = targetlongitude + tolerance_eastwest;
mlongitude = targetlongitude - tolerance_eastwest;
targetlatitude = GEOSAT.Earth.Latitude;
Mlatitude = targetlatitude + tolerance_northsouth;
mlatitude = targetlatitude - tolerance_northsouth;
sat_INC = GEOSAT.EarthMJ2000Eq.INC;
MINC = sat_INC + tolerance_northsouth;
mINC = sat_INC - tolerance_northsouth;
targetECC = GEOSAT.Earth.ECC;
MECC = targetECC + tolereance_ecc;
mECC = targetECC - tolereance_ecc;
X = targetlongitude;
Y = targetlatitude;




Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = 86400};

While GEOSAT.ElapsedDays < daysofOK
   
   Propagate DefaultProp(GEOSAT) {GEOSAT.EarthMJ2000Eq.Z = 0};
   
   Y = tolerance_northsouth* 0.5;
   If GEOSAT.EarthMJ2000Eq.INC > Y
      If GEOSAT.EarthMJ2000Eq.VZ > 0
         burnduration = 1600;
         BeginFiniteBurn FiniteBurn4(GEOSAT);
         Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
         EndFiniteBurn FiniteBurn4(GEOSAT);
      
      EndIf;
      
      If GEOSAT.EarthMJ2000Eq.VZ < 0
         burnduration = 1600;
         BeginFiniteBurn FiniteBurn3(GEOSAT);
         Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
         EndFiniteBurn FiniteBurn3(GEOSAT);
      
      EndIf;
   EndIf;
   
   
   
   X = targetlongitude + 0.5 * tolerance_eastwest;
   If GEOSAT.Earth.Longitude > X
      eLONG = targetlongitude - GEOSAT.Earth.Longitude;
      burnduration = 1600 + eLONG*50;
      BeginFiniteBurn FiniteBurn1(GEOSAT);
      Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
      EndFiniteBurn FiniteBurn1(GEOSAT);
      burnduration = (1600 + eLONG*50)/2;
      Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
      eLONG = GEOSAT.Earth.Longitude - targetlongitude;
   
   
   EndIf;
   
   
   
   Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = 1200};
   
   X = targetlongitude - 0.5 * tolerance_eastwest;
   
   If GEOSAT.Earth.Longitude < X
      eLONG = targetlongitude - GEOSAT.Earth.Longitude;
      burnduration = 1600 + eLONG*50;
      BeginFiniteBurn FiniteBurn2(GEOSAT);
      Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
      EndFiniteBurn FiniteBurn2(GEOSAT);
      burnduration = (1600 + eLONG*50)/2;
      Propagate DefaultProp(GEOSAT) {GEOSAT.ElapsedSecs = burnduration};
      eLONG = targetlongitude - GEOSAT.Earth.Longitude;
   
   EndIf;





EndWhile;
   
   




