from pathlib import Path


PATH = Path(r"C:\Users\justl\Desktop\ST50-LEBOURG_Justine_V2_editable.md")
text = PATH.read_text(encoding="utf-8")

section_333 = """#### 3.3.3 Skills-based web orchestration baseline

The third AI prototype was the most structured of the early projects. It started from an existing project developed by another laboratory team. This inherited baseline already provided a frontend, a backend, a connection to Codex and a mechanism able to read skill files. It was therefore not a blank project and should not be presented as one. Its importance for this internship was that it exposed a complete architecture for AI-assisted engineering workflows beyond the isolated Python wrappers developed previously.

*Figure 27 : architecture of the project given*

The inherited platform separated the user request, orchestration instructions and executable engineering actions. Its skills gave the model contextual instructions for bounded tasks, such as mission definition, script construction, iteration and result analysis. This architecture showed how an AI system could route a request toward a structured engineering workflow rather than expose implementation details directly to the user.

In this context, a skill is a structured instruction package describing a bounded capability: its purpose, permitted inputs, expected outputs, available commands, constraints and validation rules. An orchestrator can use these descriptions to route a request toward one or several authorised actions. This modularity was attractive because it made responsibilities explicit and suggested a path for adding new disciplines.

My work on this platform focused on the backend. Python-driven tests submitted mission requests, inspected the files generated by the skills, and evaluated the resulting GMAT workflow. This made it possible to observe how a large language model can use documented tools: it can interpret a request, identify a relevant capability, select an action, inspect generated artefacts, and produce an explanation based on the available outputs.

*Figure 28 : prompt send in the python script*

The GMAT-OPALIS pipeline demonstrations showed that the system could progress from a prompt to GMAT, then from GMAT to Simu-CIC and finally from Simu-CIC to OPALIS on controlled electrical cases. This was a proof of interoperability and orchestration, not a claim that the pipeline was generic for every satellite and mission type.

*Figure 29 : GMAT-OPALIS pipeline*

The experiment was valuable as a study of AI-agent behaviour in an engineering context. It clarified the role that an LLM may play when a user request is incomplete, when several possible tools must be selected, or when saved results need to be interpreted. It also revealed a practical limitation: the model frequently attempted to diagnose and resolve implementation errors that were in fact caused by incomplete scripts, incorrect file paths, unavailable dependencies, or poorly defined tool interfaces. In these situations, additional LLM reasoning did not make the calculation more reliable; it often added latency before the underlying technical issue could be identified and corrected deterministically.

"""

section_334 = """#### 3.3.4 Lessons from the skills-based prototype and redesign decision

The central conclusion of these experiments is that an LLM must be guided by capabilities that engineers themselves understand, can execute, and can verify without the model. It should not be expected to perform “magical” actions or compensate for an incomplete tool interface, an ambiguous data model, or an unreliable script. When these foundations are missing, the model may generate plausible explanations, but it cannot guarantee a physically valid or reproducible engineering result.

This insight justified the development of a user-oriented deterministic demonstrator. Building the demonstrator made it possible to identify which mission and satellite values can be safely modified, which values are coupled and require additional engineering review, which information must be stored for each run, and where validation checks are necessary. In other words, the deterministic workflow was not a step away from AI; it was the work required to make a future AI integration meaningful and reliable.

The skills-based approach can now be used more appropriately. Rather than asking an LLM to reconstruct and debug a complete calculation workflow at every request, a future agent can be given access to validated deterministic capabilities through clearly documented skills. It can then understand a user’s need, select an appropriate workflow, request missing information, launch authorised analyses, compare saved alternatives, and explain the available evidence. The LLM remains an orchestration and interaction layer, while the underlying engineering calculations remain explicit, testable, and under engineer control.

"""

start_333 = text.index("#### 3.3.3 Skills-based web orchestration baseline")
start_334 = text.index("#### 3.3.4 Lessons from the skills-based prototype and redesign decision")
start_34 = text.index("### 3.4 Rebuilding a user-oriented and traceable demonstrator")
text = text[:start_333] + section_333 + section_334 + text[start_34:]
PATH.write_text(text, encoding="utf-8")
print(PATH)
