import { useEffect, useMemo, useState } from 'react'
import { getElectricPropulsionTimeSeries, type ElectricPropulsionTimeSeriesSample } from './electricPropulsionApi'
import { listMissionTemplateFiles } from './missionTemplateRuntime'
import type { GmatMissionTemplateId } from './gmatMissionTemplates'
import { getOrbitKeepingTimeSeries, type OrbitKeepingTimeSeriesSample } from './orbitKeepingApi'
import { getOpalisResults, type OpalisResultSummary } from './simuCicApi'
import { requestApiJson } from '../../app/apiClient'

type PlottableTemplate = Extract<GmatMissionTemplateId, 'electric-propulsion-transfer' | 'orbit-keeping'>
type Metric = 'altitudeKm' | 'eccentricity' | 'fuelMassKg' | 'massFlowRateKgPerSec' | 'powerAvailableKw' | 'semiMajorAxisKm'
type AnalysisSample = { altitudeKm?: number; eccentricity: number; elapsedDays: number; fuelMassKg: number; massFlowRateKgPerSec?: number; powerAvailableKw?: number; semiMajorAxisKm: number }
type RunOption = { label: string; path: string; template: PlottableTemplate }
type ChartSeries = { color: string; label: string; samples: AnalysisSample[] }

const METRICS: Record<Metric, { label: string; unit: string }> = {
  altitudeKm: { label: 'Altitude', unit: 'km' }, eccentricity: { label: 'Eccentricity', unit: '' }, fuelMassKg: { label: 'Fuel mass', unit: 'kg' }, massFlowRateKgPerSec: { label: 'Mass flow rate', unit: 'kg/s' }, powerAvailableKw: { label: 'Thrust power available', unit: 'kW' }, semiMajorAxisKm: { label: 'Semi-major axis', unit: 'km' },
}
const ELECTRIC_METRICS: Metric[] = ['semiMajorAxisKm', 'eccentricity', 'fuelMassKg', 'powerAvailableKw', 'massFlowRateKgPerSec']
const ORBIT_METRICS: Metric[] = ['altitudeKm', 'semiMajorAxisKm', 'fuelMassKg']

function isPlottableTemplate(value: string): value is PlottableTemplate { return value === 'electric-propulsion-transfer' || value === 'orbit-keeping' }
function runLabel(path: string) { return path.replace(/\\/gu, '/').split('/').at(-1) ?? path }
function axisTicks(minimum: number, maximum: number, count = 5) { const span = maximum - minimum || 1; return Array.from({ length: count + 1 }, (_, index) => minimum + span * index / count) }
function axisValue(value: number) { const magnitude = Math.abs(value); return magnitude > 0 && magnitude < .01 ? value.toExponential(2) : magnitude >= 1000 ? value.toFixed(0) : magnitude >= 10 ? value.toFixed(1) : value.toFixed(2) }
function hasMetric(sample: AnalysisSample, metric: Metric): sample is AnalysisSample & Record<Metric, number> { return typeof sample[metric] === 'number' && Number.isFinite(sample[metric]) }

function LineChart({ metric, series }: { metric: Metric; series: ChartSeries[] }) {
  const width = 760; const height = 300; const margin = { bottom: 58, left: 74, right: 24, top: 26 }; const chartWidth = width - margin.left - margin.right; const chartHeight = height - margin.top - margin.bottom
  const usable = series.map(entry => ({ ...entry, samples: entry.samples.filter(sample => hasMetric(sample, metric)) })).filter(entry => entry.samples.length)
  const samples = usable.flatMap(entry => entry.samples)
  if (!samples.length) return <p className="gmat-analysis-note">This GMAT report does not contain {METRICS[metric].label.toLowerCase()} samples.</p>
  const xValues = samples.map(sample => sample.elapsedDays); const yValues = samples.map(sample => sample[metric]); const xMin = Math.min(...xValues); const xMax = Math.max(...xValues); const yMin = Math.min(...yValues); const yMax = Math.max(...yValues); const xSpan = xMax - xMin || 1; const ySpan = yMax - yMin || 1
  const x = (value: number) => margin.left + (value - xMin) / xSpan * chartWidth; const y = (value: number) => margin.top + chartHeight - (value - yMin) / ySpan * chartHeight
  const xTicks = axisTicks(xMin, xMax); const yTicks = axisTicks(yMin, yMax); const unit = METRICS[metric].unit
  return <><svg aria-label={`${METRICS[metric].label} from GMAT output`} className="gmat-analysis-chart" viewBox={`0 0 ${width} ${height}`} role="img">
    <g className="gmat-analysis-grid">{yTicks.map(tick => <line key={`y-${tick}`} x1={margin.left} x2={width - margin.right} y1={y(tick)} y2={y(tick)} />)}{xTicks.map(tick => <line key={`x-${tick}`} x1={x(tick)} x2={x(tick)} y1={margin.top} y2={height - margin.bottom} />)}</g>
    <line x1={margin.left} x2={margin.left} y1={margin.top} y2={height - margin.bottom} /><line x1={margin.left} x2={width - margin.right} y1={height - margin.bottom} y2={height - margin.bottom} />
    {yTicks.map(tick => <text key={`yl-${tick}`} textAnchor="end" x={margin.left - 8} y={y(tick) + 4}>{axisValue(tick)}</text>)}{xTicks.map(tick => <text key={`xl-${tick}`} textAnchor="middle" x={x(tick)} y={height - margin.bottom + 20}>{axisValue(tick)}</text>)}
    <text textAnchor="middle" x={margin.left + chartWidth / 2} y={height - 10}>Elapsed time (days)</text><text textAnchor="middle" transform={`translate(18 ${margin.top + chartHeight / 2}) rotate(-90)`}>{METRICS[metric].label}{unit ? ` (${unit})` : ''}</text>
    {usable.map(entry => <polyline fill="none" key={entry.label} points={entry.samples.map(sample => `${x(sample.elapsedDays)},${y(sample[metric])}`).join(' ')} stroke={entry.color} strokeWidth="3" />)}
  </svg>{usable.length > 1 ? <div className="gmat-analysis-legend">{usable.map(entry => <span key={entry.label}><i style={{ background: entry.color }} />{entry.label}</span>)}</div> : null}</>
}

function orbitSamples(samples: OrbitKeepingTimeSeriesSample[]): AnalysisSample[] { const first = samples[0]?.epochA1ModJulian ?? 0; return samples.map(sample => ({ altitudeKm: sample.altitudeKm, eccentricity: sample.eccentricity, elapsedDays: sample.epochA1ModJulian - first, fuelMassKg: sample.fuelMassKg, semiMajorAxisKm: sample.semiMajorAxisKm })) }
function electricSamples(samples: ElectricPropulsionTimeSeriesSample[]): AnalysisSample[] { return samples.map(sample => ({ eccentricity: sample.eccentricity, elapsedDays: sample.elapsedDays, fuelMassKg: sample.fuelMassKg, massFlowRateKgPerSec: sample.massFlowRateKgPerSec, powerAvailableKw: sample.powerAvailableKw, semiMajorAxisKm: sample.semiMajorAxisKm })) }
function metricRange(samples: AnalysisSample[], metric: Metric) { const values = samples.filter(sample => hasMetric(sample, metric)).map(sample => sample[metric]); return values.length ? { maximum: Math.max(...values), minimum: Math.min(...values) } : null }
function finalMetric(samples: AnalysisSample[], metric: Metric) { const sample = [...samples].reverse().find(item => hasMetric(item, metric)); return sample?.[metric] ?? null }
function metricValue(value: number | null, unit = '', digits = 1) { return value === null ? 'Unavailable' : `${value.toFixed(digits)}${unit ? ` ${unit}` : ''}` }

function OpalisResultsCard({ result }: { result: OpalisResultSummary }) { return <section className="opalis-results-card"><strong>OPALIS electrical results</strong><span>Calculated from this run&apos;s CIC ephemeris and satellite.json configuration.</span><div className="gmat-analysis-metrics"><span>Initial SoC: {metricValue(result.initialSocPercent, '%')}</span><span>Final SoC: {metricValue(result.finalSocPercent, '%')}</span><span>Max depth of discharge: {metricValue(result.maxDepthOfDischargePercent, '%')}</span><span>Solar energy: {metricValue(result.solarArrayEnergy, ' Wh', 2)}</span></div><p className={result.stopCondition === 'eBattMin reached' ? 'opalis-result-warning' : 'opalis-result-info'}>Stop condition: {result.stopCondition ?? 'Unavailable'}</p></section> }
async function loadSamples(run: RunOption) { return run.template === 'electric-propulsion-transfer' ? getElectricPropulsionTimeSeries(run.path).then(electricSamples) : getOrbitKeepingTimeSeries(run.path).then(orbitSamples) }

export function GmatAnalysisPanel({ runPath, template, workspaceDir }: { runPath?: string; template?: GmatMissionTemplateId; workspaceDir?: string | null }) {
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [metric, setMetric] = useState<Metric>('altitudeKm'); const [runs, setRuns] = useState<RunOption[]>([]); const [selectedPath, setSelectedPath] = useState(runPath ?? ''); const [comparisonPath, setComparisonPath] = useState(''); const [primarySamples, setPrimarySamples] = useState<AnalysisSample[]>([]); const [comparisonSamples, setComparisonSamples] = useState<AnalysisSample[]>([]); const [opalisResult, setOpalisResult] = useState<OpalisResultSummary | null>(null); const [vtsStatus, setVtsStatus] = useState('')
  useEffect(() => { let cancelled = false; void listMissionTemplateFiles(workspaceDir).then(files => { if (cancelled) return; const entries = files.reduce<Array<RunOption & { mtimeMs: number }>>((collected, file) => { const fileTemplate = file.missionType; if (file.kind === 'timeseries' && file.runPath && isPlottableTemplate(fileTemplate)) collected.push({ label: runLabel(file.runPath), mtimeMs: file.mtimeMs, path: file.runPath, template: fileTemplate }); return collected }, []); const activeTemplate = template && isPlottableTemplate(template) ? template : null; if (runPath && activeTemplate) entries.unshift({ label: runLabel(runPath), mtimeMs: Number.MAX_SAFE_INTEGER, path: runPath, template: activeTemplate }); const unique: RunOption[] = entries.sort((a, b) => b.mtimeMs - a.mtimeMs).filter((entry, index, all) => all.findIndex(candidate => candidate.path === entry.path) === index).map(({ label, path, template: itemTemplate }) => ({ label, path, template: itemTemplate })); setRuns(unique); setSelectedPath(current => unique.some(entry => entry.path === current) ? current : unique[0]?.path ?? '') }).catch(reason => { if (!cancelled) setError(reason instanceof Error ? reason.message : 'Unable to list GMAT runs') }); return () => { cancelled = true } }, [runPath, template, workspaceDir])
  const selectedRun = runs.find(run => run.path === selectedPath); const compatibleRuns = selectedRun ? runs.filter(run => run.template === selectedRun.template && run.path !== selectedRun.path) : []
  useEffect(() => { if (comparisonPath && !compatibleRuns.some(run => run.path === comparisonPath)) setComparisonPath('') }, [comparisonPath, compatibleRuns])
  useEffect(() => { let cancelled = false; if (!selectedRun) { setPrimarySamples([]); setComparisonSamples([]); setOpalisResult(null); return () => { cancelled = true } }; const compare = compatibleRuns.find(run => run.path === comparisonPath); setLoading(true); setError(''); void Promise.all([loadSamples(selectedRun), compare ? loadSamples(compare) : Promise.resolve([])]).then(([primary, comparison]) => { if (!cancelled) { setPrimarySamples(primary); setComparisonSamples(comparison) } }).catch(reason => { if (!cancelled) setError(reason instanceof Error ? reason.message : 'Unable to load GMAT time-series data') }).finally(() => { if (!cancelled) setLoading(false) }); void getOpalisResults(selectedRun.path).then(result => { if (!cancelled) setOpalisResult(result) }).catch(() => { if (!cancelled) setOpalisResult(null) }); return () => { cancelled = true } }, [comparisonPath, selectedRun?.path])
  const isElectric = selectedRun?.template === 'electric-propulsion-transfer'; const available = isElectric ? ELECTRIC_METRICS : ORBIT_METRICS; const selectedMetric = available.includes(metric) ? metric : available[0]; const series: ChartSeries[] = [{ color: '#60a5fa', label: `Run A · ${selectedRun?.label ?? ''}`, samples: primarySamples }, ...(comparisonPath ? [{ color: '#f59e0b', label: `Run B · ${compatibleRuns.find(run => run.path === comparisonPath)?.label ?? ''}`, samples: comparisonSamples }] : [])]; const summary = useMemo(() => metricRange(primarySamples, selectedMetric), [primarySamples, selectedMetric]); const metrics = isElectric ? ELECTRIC_METRICS.filter(key => series.some(entry => entry.samples.some(sample => hasMetric(sample, key)))) : [selectedMetric]; const deltas = comparisonPath ? available.flatMap(key => { const left = finalMetric(primarySamples, key); const right = finalMetric(comparisonSamples, key); return left === null || right === null ? [] : [{ key, value: left - right }] }) : []
  const openVts = async () => { if (!selectedRun) return; setVtsStatus('Preparing the GMAT ephemeris for VTS…'); try { const result = await requestApiJson<{ samples: number }>('/vts/open-orbit', { body: JSON.stringify({ runPath: selectedRun.path }), headers: { 'Content-Type': 'application/json' }, method: 'POST' }); setVtsStatus(`VTS opened with ${result.samples} real GMAT position samples.`) } catch (reason) { setVtsStatus(reason instanceof Error ? reason.message : 'Unable to open VTS') } }
  return <div className="gmat-analysis-panel"><section className="gmat-analysis-run-selector"><div><strong>GMAT results</strong><span>Curves use only saved GMAT time-series output from each run.</span></div><label>Run A<select value={selectedPath} onChange={event => setSelectedPath(event.target.value)}><option value="">Choose a GMAT run…</option>{runs.map(run => <option key={run.path} value={run.path}>{run.template === 'orbit-keeping' ? 'Orbit keeping' : 'Electric transfer'} · {run.label}</option>)}</select></label><label>Compare with<select disabled={!compatibleRuns.length} value={comparisonPath} onChange={event => setComparisonPath(event.target.value)}><option value="">No comparison</option>{compatibleRuns.map(run => <option key={run.path} value={run.path}>{run.label}</option>)}</select></label></section>{!selectedRun ? <div className="agent-empty-state">Run GMAT first. Results appear here once a real time-series file exists.</div> : null}{loading ? <div className="agent-empty-state">Loading saved GMAT time-series data…</div> : null}{error ? <div className="agent-empty-state">{error}</div> : null}{selectedRun && !loading && !error ? <>{opalisResult ? <OpalisResultsCard result={opalisResult} /> : null}<section className="gmat-analysis-run-summary"><strong>{comparisonPath ? 'Run A / Run B comparison' : 'Selected GMAT run'}</strong><span>{primarySamples.length} real samples from {selectedRun.label}{comparisonPath ? ` · ${comparisonSamples.length} samples from ${compatibleRuns.find(run => run.path === comparisonPath)?.label ?? 'Run B'}` : ''}</span>{deltas.length ? <div className="gmat-analysis-comparison-deltas">{deltas.map(delta => <span key={delta.key}>Δ final {METRICS[delta.key].label}: {delta.value >= 0 ? '+' : ''}{axisValue(delta.value)} {METRICS[delta.key].unit}</span>)}</div> : null}<button className="gmat-vts-launch" onClick={() => { void openVts() }} type="button">Open orbit in VTS</button>{vtsStatus ? <small className={vtsStatus.startsWith('VTS opened') ? 'is-success' : undefined}>{vtsStatus}</small> : null}</section>{metrics.map(key => { const range = metricRange(primarySamples, key); return <section key={key}><strong>{METRICS[key].label} vs elapsed time</strong><span>GMAT report output · same axis for all selected runs</span><LineChart metric={key} series={series} />{range ? <div className="gmat-analysis-metrics"><span>Run A minimum: {axisValue(range.minimum)} {METRICS[key].unit}</span><span>Run A maximum: {axisValue(range.maximum)} {METRICS[key].unit}</span></div> : null}</section> })}{!isElectric && summary ? <div className="gmat-analysis-metric-picker">{available.map(key => <button className={selectedMetric === key ? 'active' : ''} key={key} onClick={() => setMetric(key)} type="button">{METRICS[key].label}</button>)}</div> : null}</> : null}</div>
}
