import { spawn } from "node:child_process"
import fs from "node:fs/promises"
import path from "node:path"

import type { FastifyInstance } from "fastify"

import { toGmatNativePath } from "../gmat/orbitKeepingRunner.js"
import { getRequestUserWorkspaceRoot } from "../server/requestContext.js"
import { getErrorMessage, isPathInside } from "../shared/index.js"

type RunBody = { runPath?: unknown }

type OemPosition = {
  iso: string
  seconds: number
  mjd: number
  xKm: number
  yKm: number
  zKm: number
}

export type VtsTrajectory = {
  frame: "EarthMJ2000Eq"
  positions: OemPosition[]
}

function vtsHomeForHost() {
  const configured = process.env.VTS_HOME?.trim() || "D:\\STAGE\\APP\\Vts-WindowsNT-64bits-3.10.1"
  if (process.platform === "win32") return configured
  const normalized = configured.replace(/\\/gu, "/")
  const windowsPath = /^([a-z]):\/(.*)$/iu.exec(normalized)
  return windowsPath ? `/mnt/${windowsPath[1].toLowerCase()}/${windowsPath[2]}` : configured
}

function resolveGmatRunDir(root: string, candidate: unknown) {
  if (typeof candidate !== "string" || !candidate.trim()) return null
  const runDir = path.resolve(root, candidate)
  const normalized = runDir.split(path.sep).join("/")
  return isPathInside(root, runDir) && /\/gmat\/(?:orbit-keeping|electric-propulsion-transfer|mission-runs)\/[^/]+$/u.test(normalized)
    ? runDir
    : null
}

function xml(value: string) {
  return value.replace(/[<>&"']/gu, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&apos;" })[character]!)
}

function mjdFromUtc(date: Date) {
  return date.getTime() / 86_400_000 + 40_587
}

function readOemPositions(source: string): OemPosition[] {
  const positions: OemPosition[] = []
  for (const rawLine of source.split(/\r?\n/u)) {
    const values = rawLine.trim().split(/\s+/u)
    if (values.length < 4 || !/^\d{4}-\d{2}-\d{2}T/u.test(values[0])) continue
    const date = new Date(values[0].endsWith("Z") ? values[0] : `${values[0]}Z`)
    const [xKm, yKm, zKm] = values.slice(1, 4).map(Number)
    if (!Number.isFinite(date.getTime()) || [xKm, yKm, zKm].some(value => !Number.isFinite(value))) continue
    const mjdValue = mjdFromUtc(date)
    const mjd = Math.floor(mjdValue)
    positions.push({ iso: date.toISOString().replace(/\.\d{3}Z$/u, "Z"), mjd, seconds: (mjdValue - mjd) * 86_400, xKm, yKm, zKm })
  }
  return positions
}

/**
 * Reads the GMAT OEM artifact without generating any secondary file.  VTS and
 * the browser Cesium viewer both consume this exact same trajectory, so the
 * displayed orbit always remains tied to the run's saved GMAT output.
 */
export async function loadVtsTrajectory(runDir: string): Promise<VtsTrajectory> {
  const ephemerisPath = path.join(runDir, "EphemerisFile1.oem")
  const oem = await fs.readFile(ephemerisPath, "utf8").catch(() => null)
  if (!oem) throw new Error("GMAT OEM ephemeris is missing. Run GMAT successfully before visualising the orbit.")
  const positions = readOemPositions(oem)
  if (positions.length < 2) throw new Error("GMAT OEM ephemeris does not contain enough position samples to visualise the orbit.")
  return { frame: "EarthMJ2000Eq", positions }
}

async function satelliteName(runDir: string) {
  const source = await fs.readFile(path.join(runDir, "satellite.json"), "utf8").catch(() => "{}")
  let document: { satellite?: { identity?: { name?: unknown } } } = {}
  try { document = JSON.parse(source || "{}") as typeof document } catch { /* use the generic VTS label */ }
  return typeof document.satellite?.identity?.name === "string" && document.satellite.identity.name.trim()
    ? document.satellite.identity.name.replace(/[\r\n]+/gu, " ").trim()
    : "GMAT satellite"
}

function createVtsProject(name: string, start: OemPosition, end: OemPosition) {
  const escapedName = xml(name)
  return `<?xml version="1.0" encoding="UTF-8"?>
<Project Revision="7287">
 <General Name="${escapedName}" StartDateTime="${start.mjd} ${start.seconds.toFixed(6)}" EndDateTime="${end.mjd} ${end.seconds.toFixed(6)}"/>
 <MetaData><Description>GMAT trajectory visualisation generated by the digital thread.</Description></MetaData>
 <StartOptions TimeRatio="60" UseStateTimeRatio="0" SysTimeSynced="0" Paused="0" Looped="1" Minimized="0" Hidden="0" AutoClosed="0"/>
 <TimelineOptions ProjectLocked="0" CursorLocked="0" CursorRatio="0" ViewStart="${start.mjd} ${start.seconds.toFixed(6)}" ViewSpan="0" DateFormat="ISODate"><TimelineScenario Name="Scenario" Pos="0" Size="23"/><TimelineFile Name="GMAT_OEM_POSITION.TXT" Pos="1" Size="23" Mode="DEFAULT" Overlay="true"/></TimelineOptions>
 <ToBeUsedApps><Application Name="Celestia" Id="1" AutoStarted="1"/></ToBeUsedApps>
 <Entities>
  <Body Name="Earth" ParentPath="Sol"><EphemerisMode Mode="Default"/></Body>
  <Satellite Name="${escapedName}" ParentPath="Sol/Earth">
   <CommonProp><OrbitPath Color="0 0.976471 0.145098" PenStyle="SolidLine" PenWidth="2"/></CommonProp>
   <Prop2d><Icon Anchor="CENTER" Size="MEDIUM" Opacity="100"><Font Size="MEDIUM" Color="1 1 1"/><ImageLayer Type="Default"/></Icon></Prop2d>
   <Track Color="1 0 0.99266" PenStyle="SolidLine" PenWidth="2"/>
   <Component Name="${escapedName}"><Geometry><Position><Value><File Name="Data/GMAT_OEM_POSITION.TXT"/></Value></Position><Orientation><Quaternion><Value><Fixed Data="1 0 0 0"/></Value></Quaternion></Orientation></Geometry></Component>
  </Satellite>
 </Entities>
</Project>
`
}

export async function prepareVtsProject(runDir: string) {
  const { positions } = await loadVtsTrajectory(runDir)
  const root = path.join(runDir, "vts")
  const dataDir = path.join(root, "Data")
  await fs.mkdir(dataDir, { recursive: true })
  const cic = [
    "CIC_OEM_VERS = 2.0",
    `CREATION_DATE = ${new Date().toISOString().replace(/\.\d{3}Z$/u, "Z")}`,
    "ORIGINATOR = GMAT DIGITAL THREAD",
    "",
    "META_START",
    "",
    `OBJECT_NAME = ${await satelliteName(runDir)}`,
    "OBJECT_ID = GMAT-SATELLITE",
    "",
    "CENTER_NAME = EARTH",
    "REF_FRAME = EME2000",
    "TIME_SYSTEM = UTC",
    "",
    "META_STOP",
    "",
    ...positions.map(position => `${position.mjd} ${position.seconds.toFixed(6)} ${position.xKm.toExponential(12)} ${position.yKm.toExponential(12)} ${position.zKm.toExponential(12)}`),
    "",
  ].join("\n")
  const name = await satelliteName(runDir)
  const projectPath = path.join(root, "gmat-orbit.vts")
  const ephemerisOutput = path.join(dataDir, "GMAT_OEM_POSITION.TXT")
  await Promise.all([
    fs.writeFile(ephemerisOutput, cic, "utf8"),
    fs.writeFile(projectPath, createVtsProject(name, positions[0], positions.at(-1)!), "utf8"),
  ])
  return { ephemerisOutput, projectPath, samples: positions.length }
}

export async function vtsRoutes(fastify: FastifyInstance) {
  fastify.post<{ Body: RunBody }>("/api/vts/trajectory", async (req, reply) => {
    const root = getRequestUserWorkspaceRoot()
    const runDir = root ? resolveGmatRunDir(path.resolve(root), req.body?.runPath) : null
    if (!root) return reply.status(500).send({ error: "user workspace is unavailable" })
    if (!runDir) return reply.status(400).send({ error: "invalid GMAT run path" })
    try {
      const trajectory = await loadVtsTrajectory(runDir)
      return reply.send({ ...trajectory, samples: trajectory.positions.length })
    } catch (error) {
      return reply.status(422).send({ error: getErrorMessage(error, "failed to load GMAT trajectory") })
    }
  })

  fastify.post<{ Body: RunBody }>("/api/vts/open-orbit", async (req, reply) => {
    const root = getRequestUserWorkspaceRoot()
    const runDir = root ? resolveGmatRunDir(path.resolve(root), req.body?.runPath) : null
    if (!root) return reply.status(500).send({ error: "user workspace is unavailable" })
    if (!runDir) return reply.status(400).send({ error: "invalid GMAT run path" })
    try {
      const prepared = await prepareVtsProject(runDir)
      const executable = path.join(vtsHomeForHost(), "startVTS.exe")
      await fs.access(executable)
      await new Promise<void>((resolve, reject) => {
        const child = spawn(executable, ["--batch", "--project", toGmatNativePath(prepared.projectPath)], { detached: true, stdio: "ignore", windowsHide: false })
        child.once("error", reject)
        child.once("spawn", () => { child.unref(); resolve() })
      })
      return reply.send({ ephemeris: path.relative(root, prepared.ephemerisOutput), ok: true, project: path.relative(root, prepared.projectPath), samples: prepared.samples })
    } catch (error) {
      return reply.status(422).send({ error: getErrorMessage(error, "failed to open VTS") })
    }
  })
}
